@REM #########################################################################
@REM #
@REM #  Copyright 2012 - 2019 Vivante Corporation, Santa Clara, California.
@REM #  All Rights Reserved.
@REM #
@REM #  Permission is hereby granted, free of charge, to any person obtaining
@REM #  a copy of this software and associated documentation files (the
@REM #  'Software'), to deal in the Software without restriction, including
@REM #  without limitation the rights to use, copy, modify, merge, publish,
@REM #  distribute, sub license, and/or sell copies of the Software, and to
@REM #  permit persons to whom the Software is furnished to do so, subject
@REM #  to the following conditions:
@REM #
@REM #  The above copyright notice and this permission notice (including the
@REM #  next paragraph) shall be included in all copies or substantial
@REM #  portions of the Software.
@REM #
@REM #  THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND,
@REM #  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
@REM #  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT.
@REM #  IN NO EVENT SHALL VIVANTE AND/OR ITS SUPPLIERS BE LIABLE FOR ANY
@REM #  CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
@REM #  TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
@REM #  SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
@REM #
@REM #########################################################################


if "%1"=="" goto :usage
set CONFIG=%1

galRunTest2.exe gal2DAlphaBlending001.dll -c %CONFIG%
galRunTest2.exe gal2DAlphaBlending002.dll -c %CONFIG%
galRunTest2.exe gal2DAlphaBlending003.dll -c %CONFIG%
galRunTest2.exe gal2DAlphaBlending004.dll -c %CONFIG%
galRunTest2.exe gal2DAlphaBlending005.dll -c %CONFIG%
galRunTest2.exe gal2DAlphaBlending006.dll -c %CONFIG%
galRunTest2.exe gal2DAlphaBlending007.dll -c %CONFIG%
galRunTest2.exe gal2DAlphaBlendingYUV001.dll -c %CONFIG%
galRunTest2.exe gal2DAlphaBlendingYUV002.dll -c %CONFIG%
galRunTest2.exe gal2DAlphablendFilterBlit001.dll -c %CONFIG%
galRunTest2.exe gal2DAlphablendFilterBlit002.dll -c %CONFIG%
galRunTest2.exe gal2DAlphablendFilterBlit003.dll -c %CONFIG%
galRunTest2.exe gal2DAlphablendFilterBlit004.dll -c %CONFIG%
galRunTest2.exe gal2DAlphablendFilterBlit005.dll -c %CONFIG%
galRunTest2.exe gal2DAlphablendFilterBlit006.dll -c %CONFIG%
galRunTest2.exe gal2DAlphablendFilterBlit011.dll -c %CONFIG%
galRunTest2.exe gal2DAlphablendFilterBlit012.dll -c %CONFIG%
galRunTest2.exe gal2DAlphablendFilterBlit013.dll -c %CONFIG%
galRunTest2.exe gal2DAlphablendFilterBlit014.dll -c %CONFIG%
galRunTest2.exe gal2DAlphablendFilterBlit015.dll -c %CONFIG%
galRunTest2.exe gal2DAlphablendFilterBlit016.dll -c %CONFIG%
galRunTest2.exe gal2DAlphablendFilterBlit017.dll -c %CONFIG%
galRunTest2.exe gal2DAlphablendFilterBlit018.dll -c %CONFIG%
galRunTest2.exe gal2DAlphablendFilterBlit021.dll -c %CONFIG%
galRunTest2.exe gal2DAlphablendFilterBlit022.dll -c %CONFIG%
galRunTest2.exe gal2DAlphablendFilterBlit023.dll -c %CONFIG%
galRunTest2.exe gal2DAlphablendFilterBlit025.dll -c %CONFIG%
galRunTest2.exe gal2DAlphablendFilterBlit027.dll -c %CONFIG%
galRunTest2.exe gal2DAlphablendFilterBlit028.dll -c %CONFIG%
galRunTest2.exe gal2DAndroidCases001.dll -c %CONFIG%
galRunTest2.exe gal2DAndroidCases002.dll -c %CONFIG%
galRunTest2.exe gal2DAndroidCases003.dll -c %CONFIG%
galRunTest2.exe gal2DAndroidCases004.dll -c %CONFIG%
galRunTest2.exe gal2DAndroidCases005.dll -c %CONFIG%
galRunTest2.exe gal2DAndroidCases006.dll -c %CONFIG%
galRunTest2.exe gal2DAndroidCases007.dll -c %CONFIG%
galRunTest2.exe gal2DAndroidCases008.dll -c %CONFIG%
galRunTest2.exe gal2DAndroidCases009.dll -c %CONFIG%
galRunTest2.exe gal2DAntiFlicker001.dll -c %CONFIG%
galRunTest2.exe gal2DAntiFlicker002.dll -c %CONFIG%
galRunTest2.exe gal2DAntiFlicker003.dll -c %CONFIG%
galRunTest2.exe gal2DBilinearFilterMultiSourceBlit001.dll -c %CONFIG%
galRunTest2.exe gal2DBilinearFilterMultiSourceBlit002.dll -c %CONFIG%
galRunTest2.exe gal2DBilinearFilterMultiSourceBlit003.dll -c %CONFIG%
galRunTest2.exe gal2DBilinearFilterMultiSourceBlit004.dll -c %CONFIG%
galRunTest2.exe gal2DBilinearFilterMultiSourceBlit005.dll -c %CONFIG%
galRunTest2.exe gal2DBitBlit001.dll -c %CONFIG%
galRunTest2.exe gal2DBitBlit002.dll -c %CONFIG%
galRunTest2.exe gal2DBitBlit003.dll -c %CONFIG%
galRunTest2.exe gal2DBitBlit004.dll -c %CONFIG%
galRunTest2.exe gal2DBitBlit005.dll -c %CONFIG%
galRunTest2.exe gal2DBlendFactors.dll -c %CONFIG%
galRunTest2.exe gal2DBlendFactors_001.dll -c %CONFIG%
galRunTest2.exe gal2DBlendFactors_002.dll -c %CONFIG%
galRunTest2.exe gal2DBlendFactors_003.dll -c %CONFIG%
galRunTest2.exe gal2DBlitFullRotate.dll -c %CONFIG%
galRunTest2.exe gal2DClear001.dll -c %CONFIG%
galRunTest2.exe gal2DClear002.dll -c %CONFIG%
galRunTest2.exe gal2DClear003.dll -c %CONFIG%
galRunTest2.exe gal2DClear004.dll -c %CONFIG%
galRunTest2.exe gal2DClear005.dll -c %CONFIG%
galRunTest2.exe gal2DClear006.dll -c %CONFIG%
galRunTest2.exe gal2DColorBrush001.dll -c %CONFIG%
galRunTest2.exe gal2DColorBrush002.dll -c %CONFIG%
galRunTest2.exe gal2DColorBrush003.dll -c %CONFIG%
galRunTest2.exe gal2DColorBrush004.dll -c %CONFIG%
galRunTest2.exe gal2DColorKey.dll -c %CONFIG%
galRunTest2.exe gal2DColorSource001.dll -c %CONFIG%
galRunTest2.exe gal2DColorSource002.dll -c %CONFIG%
galRunTest2.exe gal2DColorSource003.dll -c %CONFIG%
galRunTest2.exe gal2DColorSource004.dll -c %CONFIG%
galRunTest2.exe gal2DColorSource005.dll -c %CONFIG%
galRunTest2.exe gal2DColorSource006.dll -c %CONFIG%
::galRunTest2.exe gal2DColorSource007.dll -c %CONFIG%
galRunTest2.exe gal2DColorSource008.dll -c %CONFIG%
galRunTest2.exe gal2DColorSource009.dll -c %CONFIG%
galRunTest2.exe gal2DColorSource010.dll -c %CONFIG%
galRunTest2.exe gal2DDestColorKeyDFBMode.dll -c %CONFIG%
galRunTest2.exe gal2DDestination001.dll -c %CONFIG%
galRunTest2.exe gal2DDestination002.dll -c %CONFIG%
galRunTest2.exe gal2DDestination003.dll -c %CONFIG%
galRunTest2.exe gal2DDestination004.dll -c %CONFIG%
galRunTest2.exe gal2DDestination005.dll -c %CONFIG%
galRunTest2.exe gal2DDestination006.dll -c %CONFIG%
galRunTest2.exe gal2DDither001.dll -c %CONFIG%
galRunTest2.exe gal2DDither002.dll -c %CONFIG%
galRunTest2.exe gal2DFilterBlit001.dll -c %CONFIG%
galRunTest2.exe gal2DFilterBlit002.dll -c %CONFIG%
galRunTest2.exe gal2DFilterBlit003.dll -c %CONFIG%
galRunTest2.exe gal2DFilterBlit004.dll -c %CONFIG%
galRunTest2.exe gal2DFilterBlit005.dll -c %CONFIG%
galRunTest2.exe gal2DFilterBlit006.dll -c %CONFIG%
galRunTest2.exe gal2DFilterBlit007.dll -c %CONFIG%
galRunTest2.exe gal2DFilterBlit008.dll -c %CONFIG%
galRunTest2.exe gal2DFilterBlit009.dll -c %CONFIG%
galRunTest2.exe gal2DFilterBlit010.dll -c %CONFIG%
galRunTest2.exe gal2DFilterBlit011.dll -c %CONFIG%
galRunTest2.exe gal2DFilterBlit012.dll -c %CONFIG%
galRunTest2.exe gal2DFilterBlit013.dll -c %CONFIG%
galRunTest2.exe gal2DFilterBlit014.dll -c %CONFIG%
galRunTest2.exe gal2DFilterBlit015.dll -c %CONFIG%
galRunTest2.exe gal2DFilterBlit016.dll -c %CONFIG%
galRunTest2.exe gal2DFilterBlit017.dll -c %CONFIG%
galRunTest2.exe gal2DFilterBlit018.dll -c %CONFIG%
galRunTest2.exe gal2DFilterBlit019.dll -c %CONFIG%
galRunTest2.exe gal2DFilterBlit020.dll -c %CONFIG%
galRunTest2.exe gal2DFilterBlit021.dll -c %CONFIG%
galRunTest2.exe gal2DFilterBlit022.dll -c %CONFIG%
galRunTest2.exe gal2DFilterBlit023.dll -c %CONFIG%
galRunTest2.exe gal2DFilterRotateDither.dll -c %CONFIG%
galRunTest2.exe gal2DFilterRotateDither002.dll -c %CONFIG%
galRunTest2.exe gal2DFilterRotateDither003.dll -c %CONFIG%
galRunTest2.exe gal2DFormat10Bit001.dll -c %CONFIG%
galRunTest2.exe gal2DFormat10Bit002.dll -c %CONFIG%
galRunTest2.exe gal2DFormat10Bit003.dll -c %CONFIG%
galRunTest2.exe gal2DFormat10Bit004.dll -c %CONFIG%
galRunTest2.exe gal2DFormat10Bit005.dll -c %CONFIG%
galRunTest2.exe gal2DFormat10Bit006.dll -c %CONFIG%
galRunTest2.exe gal2DFormatA8_001.dll -c %CONFIG%
galRunTest2.exe gal2DFormatA8_002.dll -c %CONFIG%
galRunTest2.exe gal2DFormatA8_003.dll -c %CONFIG%
galRunTest2.exe gal2DFormatA8_004.dll -c %CONFIG%
galRunTest2.exe gal2DFormatA8_005.dll -c %CONFIG%
galRunTest2.exe gal2DFormatA8_006.dll -c %CONFIG%
galRunTest2.exe gal2DFormatARGB001.dll -c %CONFIG%
galRunTest2.exe gal2DFormatARGB002.dll -c %CONFIG%
galRunTest2.exe gal2DFormatARGB003.dll -c %CONFIG%
galRunTest2.exe gal2DFormatCompressed2D001.dll -c %CONFIG%
galRunTest2.exe gal2DFormatCompressed2D002.dll -c %CONFIG%
galRunTest2.exe gal2DFormatCompressed2D003.dll -c %CONFIG%
galRunTest2.exe gal2DFormatCompressed2D004.dll -c %CONFIG%
galRunTest2.exe gal2DFormatCompressed2D005.dll -c %CONFIG%
galRunTest2.exe gal2DFormatCompressed2D006.dll -c %CONFIG%
galRunTest2.exe gal2DFormatCompressed2D007.dll -c %CONFIG%
galRunTest2.exe gal2DFormatCompressed2D008.dll -c %CONFIG%
galRunTest2.exe gal2DFormatCompressed2D009.dll -c %CONFIG%
galRunTest2.exe gal2DFormatCompressed2D010.dll -c %CONFIG%
galRunTest2.exe gal2DFormatCompressed2D011.dll -c %CONFIG%
galRunTest2.exe gal2DFormatCompressed2D012.dll -c %CONFIG%
galRunTest2.exe gal2DFormatCompressed2D013.dll -c %CONFIG%
galRunTest2.exe gal2DFormatCompressed2D014.dll -c %CONFIG%
galRunTest2.exe gal2DFormatCompressed2D015.dll -c %CONFIG%
galRunTest2.exe gal2DFormatCompressed2D016.dll -c %CONFIG%
galRunTest2.exe gal2DFormatCompressedDEC001.dll -c %CONFIG%
galRunTest2.exe gal2DFormatCompressedDEC002.dll -c %CONFIG%
galRunTest2.exe gal2DFormatCompressedDEC003.dll -c %CONFIG%
galRunTest2.exe gal2DFormatCompressedDEC004.dll -c %CONFIG%
galRunTest2.exe gal2DFormatCompressedDEC005.dll -c %CONFIG%
galRunTest2.exe gal2DFormatCompressedDEC006.dll -c %CONFIG%
galRunTest2.exe gal2DFormatCompressedDEC007.dll -c %CONFIG%
galRunTest2.exe gal2DFormatCompressedDEC008.dll -c %CONFIG%
galRunTest2.exe gal2DFormatCompressedDEC009.dll -c %CONFIG%
galRunTest2.exe gal2DFormatCompressedDEC010.dll -c %CONFIG%
galRunTest2.exe gal2DFormatCompressedDEC011.dll -c %CONFIG%
galRunTest2.exe gal2DFormatCompressedDEC012.dll -c %CONFIG%
galRunTest2.exe gal2DFormatCompressedDEC013.dll -c %CONFIG%
galRunTest2.exe gal2DFormatCompressedDEC014.dll -c %CONFIG%
galRunTest2.exe gal2DFormatCompressedDEC015.dll -c %CONFIG%
galRunTest2.exe gal2DFormatCompressedDEC016.dll -c %CONFIG%
galRunTest2.exe gal2DFormatCompressedDEC017.dll -c %CONFIG%
galRunTest2.exe gal2DFormatCompressedDEC400_001.dll -c %CONFIG%
galRunTest2.exe gal2DFormatCompressedDEC400_002.dll -c %CONFIG%
galRunTest2.exe gal2DFormatCompressedDEC400_003.dll -c %CONFIG%
galRunTest2.exe gal2DFormatCompressedDEC400_004.dll -c %CONFIG%
galRunTest2.exe gal2DFormatCompressedDEC400_005.dll -c %CONFIG%
galRunTest2.exe gal2DFormatCompressedDEC400_006.dll -c %CONFIG%
galRunTest2.exe gal2DFormatCompressedDEC400_007.dll -c %CONFIG%
galRunTest2.exe gal2DFormatCompressedDEC400_008.dll -c %CONFIG%
galRunTest2.exe gal2DFormatCompressedTPC001.dll -c %CONFIG%
galRunTest2.exe gal2DFormatCompressedTPC002.dll -c %CONFIG%
galRunTest2.exe gal2DFormatCompressedTPC003.dll -c %CONFIG%
galRunTest2.exe gal2DFormatCompressedTPC004.dll -c %CONFIG%
galRunTest2.exe gal2DFormatCompressedTPC005.dll -c %CONFIG%
galRunTest2.exe gal2DFormatCompressedTPC006.dll -c %CONFIG%
galRunTest2.exe gal2DFormatCompressedTPC007.dll -c %CONFIG%
galRunTest2.exe gal2DFormatCompressedTPC008.dll -c %CONFIG%
galRunTest2.exe gal2DFormatCompressedTPC009.dll -c %CONFIG%
galRunTest2.exe gal2DFormatCompressedTPC010.dll -c %CONFIG%
galRunTest2.exe gal2DFormatCompressedTPC011.dll -c %CONFIG%
galRunTest2.exe gal2DFormatCompressedTPC012.dll -c %CONFIG%
galRunTest2.exe gal2DFormatCompressedTPC013.dll -c %CONFIG%
galRunTest2.exe gal2DFormatCompressedTPC014.dll -c %CONFIG%
galRunTest2.exe gal2DFormatCompressedTPC015.dll -c %CONFIG%
galRunTest2.exe gal2DFormatCompressedTPC016.dll -c %CONFIG%
galRunTest2.exe gal2DFormatCompressedTPCV11_001.dll -c %CONFIG%
galRunTest2.exe gal2DFormatCompressedTPCV11_002.dll -c %CONFIG%
galRunTest2.exe gal2DFormatCompressedTPCV11_004.dll -c %CONFIG%
galRunTest2.exe gal2DFormatCompressedTPCV11_005.dll -c %CONFIG%
galRunTest2.exe gal2DFormatCompressedTPCV11_007.dll -c %CONFIG%
galRunTest2.exe gal2DFormatCompressedTPCV11_008.dll -c %CONFIG%
galRunTest2.exe gal2DFormatCompressedTPCV11_010.dll -c %CONFIG%
galRunTest2.exe gal2DFormatCompressedTPCV11_011.dll -c %CONFIG%
galRunTest2.exe gal2DFormatCompressedTPCV11_012.dll -c %CONFIG%
galRunTest2.exe gal2DFormatCompressedTPCV11_013.dll -c %CONFIG%
galRunTest2.exe gal2DFormatGamma001.dll -c %CONFIG%
galRunTest2.exe gal2DFormatGamma002.dll -c %CONFIG%
galRunTest2.exe gal2DFormatTileStatus001.dll -c %CONFIG%
galRunTest2.exe gal2DFormatTileStatus002.dll -c %CONFIG%
galRunTest2.exe gal2DFormatTileStatus003.dll -c %CONFIG%
galRunTest2.exe gal2DFormatTileStatus004.dll -c %CONFIG%
galRunTest2.exe gal2DFormatTileStatus005.dll -c %CONFIG%
galRunTest2.exe gal2DFormatTileStatus006.dll -c %CONFIG%
galRunTest2.exe gal2DFormatTileStatus007.dll -c %CONFIG%
galRunTest2.exe gal2DFormatTileStatus008.dll -c %CONFIG%
galRunTest2.exe gal2DFormatTileStatus009.dll -c %CONFIG%
galRunTest2.exe gal2DFormatTileStatus010.dll -c %CONFIG%
galRunTest2.exe gal2DFormatTileStatus011.dll -c %CONFIG%
galRunTest2.exe gal2DFormatTileStatus012.dll -c %CONFIG%
galRunTest2.exe gal2DFormatTileStatus013.dll -c %CONFIG%
galRunTest2.exe gal2DFormatTileStatus014.dll -c %CONFIG%
galRunTest2.exe gal2DFormatTileStatus015.dll -c %CONFIG%
galRunTest2.exe gal2DFormatTileStatus016.dll -c %CONFIG%
galRunTest2.exe gal2DFormatTileStatus017.dll -c %CONFIG%
galRunTest2.exe gal2DFormatTileStatus018.dll -c %CONFIG%
galRunTest2.exe gal2DFormatTiling001.dll -c %CONFIG%
galRunTest2.exe gal2DFormatTiling002.dll -c %CONFIG%
galRunTest2.exe gal2DFormatTiling003.dll -c %CONFIG%
galRunTest2.exe gal2DFormatTiling004.dll -c %CONFIG%
galRunTest2.exe gal2DFormatTiling005.dll -c %CONFIG%
galRunTest2.exe gal2DFormatTiling006.dll -c %CONFIG%
galRunTest2.exe gal2DFormatTiling007.dll -c %CONFIG%
galRunTest2.exe gal2DFormatTiling008.dll -c %CONFIG%
galRunTest2.exe gal2DFormatTiling009.dll -c %CONFIG%
galRunTest2.exe gal2DFormatTiling010.dll -c %CONFIG%
galRunTest2.exe gal2DFormatTiling011.dll -c %CONFIG%
galRunTest2.exe gal2DFormatTiling012.dll -c %CONFIG%
::galRunTest2.exe gal2DFormatTiling013.dll -c %CONFIG%
galRunTest2.exe gal2DFormatYUV001.dll -c %CONFIG%
galRunTest2.exe gal2DFormatYUV002.dll -c %CONFIG%
galRunTest2.exe gal2DFormatYUV003.dll -c %CONFIG%
galRunTest2.exe gal2DFormatYUV004.dll -c %CONFIG%
galRunTest2.exe gal2DFormatYUV005.dll -c %CONFIG%
galRunTest2.exe gal2DFormatYUV006.dll -c %CONFIG%
galRunTest2.exe gal2DFormatYUV007.dll -c %CONFIG%
galRunTest2.exe gal2DFormatYUV008.dll -c %CONFIG%
galRunTest2.exe gal2DFormatYUV009.dll -c %CONFIG%
galRunTest2.exe gal2DFormatYUV010.dll -c %CONFIG%
galRunTest2.exe gal2DFormatYUV011.dll -c %CONFIG%
galRunTest2.exe gal2DFormatYUV012.dll -c %CONFIG%
galRunTest2.exe gal2DFormatYUV013.dll -c %CONFIG%
galRunTest2.exe gal2DFormatYUV014.dll -c %CONFIG%
galRunTest2.exe gal2DFormatYUV015.dll -c %CONFIG%
galRunTest2.exe gal2DFormatYUV016.dll -c %CONFIG%
galRunTest2.exe gal2DFormatYUV017.dll -c %CONFIG%
galRunTest2.exe gal2DFormatYUV018.dll -c %CONFIG%
galRunTest2.exe gal2DFormatYUV019.dll -c %CONFIG%
galRunTest2.exe gal2DLine001.dll -c %CONFIG%
galRunTest2.exe gal2DLine002.dll -c %CONFIG%
galRunTest2.exe gal2DLine003.dll -c %CONFIG%
galRunTest2.exe gal2DLine004.dll -c %CONFIG%
galRunTest2.exe gal2DLine005.dll -c %CONFIG%
galRunTest2.exe gal2DLine006.dll -c %CONFIG%
galRunTest2.exe gal2DLine007.dll -c %CONFIG%
galRunTest2.exe gal2DLine008.dll -c %CONFIG%
galRunTest2.exe gal2DLine009.dll -c %CONFIG%
galRunTest2.exe gal2DLine010.dll -c %CONFIG%
galRunTest2.exe gal2DLine011.dll -c %CONFIG%
galRunTest2.exe gal2DMaskedBlit.dll -c %CONFIG%
galRunTest2.exe gal2DMaskedSource.dll -c %CONFIG%
galRunTest2.exe gal2DMaskedSource001.dll -c %CONFIG%
galRunTest2.exe gal2DMaskedString.dll -c %CONFIG%
galRunTest2.exe gal2DMemoryAligned001.dll -c %CONFIG%
galRunTest2.exe gal2DMemoryAligned002.dll -c %CONFIG%
galRunTest2.exe gal2DMemoryAligned003.dll -c %CONFIG%
galRunTest2.exe gal2DMemoryAligned004.dll -c %CONFIG%
galRunTest2.exe gal2DMemoryAligned005.dll -c %CONFIG%
galRunTest2.exe gal2DMemoryAligned006.dll -c %CONFIG%
galRunTest2.exe gal2DMonoBlit001.dll -c %CONFIG%
galRunTest2.exe gal2DMonoBlit002.dll -c %CONFIG%
galRunTest2.exe gal2DMonoBlit003.dll -c %CONFIG%
galRunTest2.exe gal2DMonoBlit004.dll -c %CONFIG%
galRunTest2.exe gal2DMonoSource.dll -c %CONFIG%
galRunTest2.exe gal2DMonochromeBrush001.dll -c %CONFIG%
galRunTest2.exe gal2DMonochromeBrush002.dll -c %CONFIG%
galRunTest2.exe gal2DMonochromeBrush003.dll -c %CONFIG%
galRunTest2.exe gal2DMonochromeBrush004.dll -c %CONFIG%
galRunTest2.exe gal2DMonochromeBrush005.dll -c %CONFIG%
galRunTest2.exe gal2DMonochromeSource001.dll -c %CONFIG%
galRunTest2.exe gal2DMonochromeSource002.dll -c %CONFIG%
galRunTest2.exe gal2DMonochromeSource003.dll -c %CONFIG%
galRunTest2.exe gal2DMonochromeSource004.dll -c %CONFIG%
galRunTest2.exe gal2DMonochromeSource005.dll -c %CONFIG%
galRunTest2.exe gal2DMonochromeSource006.dll -c %CONFIG%
galRunTest2.exe gal2DMonochromeSource007.dll -c %CONFIG%
galRunTest2.exe gal2DMultiSourceBlit001.dll -c %CONFIG%
galRunTest2.exe gal2DMultiSourceBlit002.dll -c %CONFIG%
galRunTest2.exe gal2DMultiSourceBlit003.dll -c %CONFIG%
galRunTest2.exe gal2DMultiSourceBlit010.dll -c %CONFIG%
galRunTest2.exe gal2DMultiSourceBlit011.dll -c %CONFIG%
galRunTest2.exe gal2DMultiSourceBlit012.dll -c %CONFIG%
galRunTest2.exe gal2DMultiSourceBlit013.dll -c %CONFIG%
galRunTest2.exe gal2DMultiSourceBlit014.dll -c %CONFIG%
galRunTest2.exe gal2DMultiSourceBlit015.dll -c %CONFIG%
galRunTest2.exe gal2DMultiSourceBlitRotation101.dll -c %CONFIG%
galRunTest2.exe gal2DMultiSourceBlitRotation102.dll -c %CONFIG%
galRunTest2.exe gal2DMultiSourceBlitRotation103.dll -c %CONFIG%
galRunTest2.exe gal2DMultiSourceBlitRotation104.dll -c %CONFIG%
galRunTest2.exe gal2DMultiSourceBlitRotation105.dll -c %CONFIG%
galRunTest2.exe gal2DMultiSourceBlitRotation106.dll -c %CONFIG%
galRunTest2.exe gal2DMultiSourceBlitRotation107.dll -c %CONFIG%
galRunTest2.exe gal2DMultiSourceBlitRotation201.dll -c %CONFIG%
galRunTest2.exe gal2DMultiSourceBlitRotation202.dll -c %CONFIG%
galRunTest2.exe gal2DMultiSourceBlitRotation203.dll -c %CONFIG%
galRunTest2.exe gal2DMultiSourceBlitRotation204.dll -c %CONFIG%
galRunTest2.exe gal2DMultiSourceBlitRotation205.dll -c %CONFIG%
galRunTest2.exe gal2DMultiSourceBlitRotation206.dll -c %CONFIG%
galRunTest2.exe gal2DMultiSourceBlitRotation207.dll -c %CONFIG%
galRunTest2.exe gal2DMultiSourceBlitStress.dll -c %CONFIG%
galRunTest2.exe gal2DMultiply001.dll -c %CONFIG%
galRunTest2.exe gal2DRotation001.dll -c %CONFIG%
galRunTest2.exe gal2DRotation002.dll -c %CONFIG%
galRunTest2.exe gal2DRotation003.dll -c %CONFIG%
galRunTest2.exe gal2DRotation004.dll -c %CONFIG%
galRunTest2.exe gal2DRotation005.dll -c %CONFIG%
galRunTest2.exe gal2DRotation006.dll -c %CONFIG%
galRunTest2.exe gal2DRotation007.dll -c %CONFIG%
galRunTest2.exe gal2DRotation008.dll -c %CONFIG%
galRunTest2.exe gal2DRotation009.dll -c %CONFIG%
galRunTest2.exe gal2DRotation010.dll -c %CONFIG%
galRunTest2.exe gal2DRotation011.dll -c %CONFIG%
galRunTest2.exe gal2DRotation012.dll -c %CONFIG%
galRunTest2.exe gal2DRotation013.dll -c %CONFIG%
galRunTest2.exe gal2DRotation014.dll -c %CONFIG%
galRunTest2.exe gal2DRotation015.dll -c %CONFIG%
galRunTest2.exe gal2DRotation016.dll -c %CONFIG%
galRunTest2.exe gal2DRotation017.dll -c %CONFIG%
galRunTest2.exe gal2DRotation018.dll -c %CONFIG%
galRunTest2.exe gal2DRotation019.dll -c %CONFIG%
galRunTest2.exe gal2DRotation020.dll -c %CONFIG%
galRunTest2.exe gal2DRotation021.dll -c %CONFIG%
galRunTest2.exe gal2DRotation022.dll -c %CONFIG%
galRunTest2.exe gal2DRotation023.dll -c %CONFIG%
galRunTest2.exe gal2DRotation024.dll -c %CONFIG%
galRunTest2.exe gal2DRotation025.dll -c %CONFIG%
galRunTest2.exe gal2DRotation026.dll -c %CONFIG%
galRunTest2.exe gal2DScaleBlit.dll -c %CONFIG%
galRunTest2.exe gal2DScaleBlit002.dll -c %CONFIG%
galRunTest2.exe gal2DSingleColorBrush001.dll -c %CONFIG%
galRunTest2.exe gal2DSingleColorBrush002.dll -c %CONFIG%
galRunTest2.exe gal2DSingleColorBrush003.dll -c %CONFIG%
galRunTest2.exe gal2DSourceColorKeyDFBMode.dll -c %CONFIG%
galRunTest2.exe gal2DStretchBlit001.dll -c %CONFIG%
galRunTest2.exe gal2DStretchBlit002.dll -c %CONFIG%
galRunTest2.exe gal2DStretchBlit003.dll -c %CONFIG%
galRunTest2.exe gal2DStretchBlit004.dll -c %CONFIG%
galRunTest2.exe gal2DStretchBlit005.dll -c %CONFIG%
galRunTest2.exe gal2DStretchBlit006.dll -c %CONFIG%
galRunTest2.exe gal2DStretchBlit007.dll -c %CONFIG%
galRunTest2.exe gal2DStretchBlit008.dll -c %CONFIG%
galRunTest2.exe gal2DStretchBlit009.dll -c %CONFIG%
galRunTest2.exe gal2DStretchBlit010.dll -c %CONFIG%
galRunTest2.exe gal2DStretchBlit011.dll -c %CONFIG%
galRunTest2.exe gal2DStretchBlit012.dll -c %CONFIG%
galRunTest2.exe gal2DStretchBlit013.dll -c %CONFIG%
galRunTest2.exe gal2DStretchBlit014.dll -c %CONFIG%
galRunTest2.exe gal2DString.dll -c %CONFIG%
galRunTest2.exe gal2DYUV2RGB.dll -c %CONFIG%

:usage
echo usage: run.bat CONFIG
echo .


:end